- cmd/flamectl/resources/design/design.go
- cmd/flamectl/resources/schema/schema.go
- go.mod
- go.sum
Remove prometheus log package as it is not used but dependabot causes
an issue due to the package.
> cleanup package with little use

- cmd/controller/app/job/default_handler.go
- cmd/controller/app/job/job_state.go
- cmd/flamectl/resources/job/job.go
a command to stop a job is implemented.
> feature: stop job

- lib/python/flame/config.py
- lib/python/flame/examples/mnist/aggregator/config.json
- lib/python/flame/examples/mnist/trainer/config.json
- lib/python/flame/mode/horizontal/middle_aggregator.py
- lib/python/flame/mode/horizontal/top_aggregator.py
- lib/python/flame/optimizer/fedadagrad.py
- lib/python/flame/optimizer/fedadam.py
- lib/python/flame/optimizer/fedopt.py
- lib/python/flame/optimizer/fedyogi.py
- lib/python/flame/optimizers.py
Added three adaptive aggregation algorithms FedAdam, FedAdaGrad, and FedYogi to the aggregator. This implementation was done in PyTorch, and Tensorflow version will be supported later.
-- | -- | --
modified | lib/python/flame/config.py | rewrote new initialization for optimizer; registered more optimizer options
modified | lib/python/flame/examples/mnist/aggregator/config.json | example config
modified | lib/python/flame/examples/mnist/trainer/config.json | example config
modified | lib/python/flame/mode/horizontal/middle_aggregator.py | passed parameters into optimizers
modified | lib/python/flame/mode/horizontal/top_aggregator.py | passed parameters into optimizers
created | lib/python/flame/optimizer/fedopt.py | abstract class of fedopt - adaptive optimizer family …
> features: add fedopt aggregation

- cmd/controller/app/controller.go
- cmd/controller/app/job/default_handler.go
- cmd/controller/app/job/handler.go
- cmd/controller/app/job/manager.go
- cmd/controller/config/config.go
- fiab/helm-chart/templates/controller-configmap.yaml
- fiab/helm-chart/templates/namespace.yaml
namespace needs to be configurable depending on different environments.
> make namespace configurable

- lib/python/flame/channel.py
- lib/python/flame/examples/hybrid/__init__.py
- lib/python/flame/examples/hybrid/aggregator/__init__.py
- lib/python/flame/examples/hybrid/aggregator/config.json
- lib/python/flame/examples/hybrid/aggregator/main.py
- lib/python/flame/examples/hybrid/trainer/__init__.py
- lib/python/flame/examples/hybrid/trainer/config_eu_german.json
- lib/python/flame/examples/hybrid/trainer/config_eu_uk.json
- lib/python/flame/examples/hybrid/trainer/config_us_east.json
- lib/python/flame/examples/hybrid/trainer/config_us_west.json
- lib/python/flame/examples/hybrid/trainer/main.py
- lib/python/flame/mode/distributed/trainer.py
- lib/python/flame/mode/horizontal/middle_aggregator.py
- lib/python/flame/mode/horizontal/top_aggregator.py
- lib/python/flame/mode/hybrid/__init__.py
- lib/python/flame/mode/hybrid/trainer.py
This commit enables hybrid mode that combines federated learning topology with local distributed learning fashion.
-- | -- | --
modified | lib/python/flame/channel.py | add a getter function
modified | lib/python/flame/examples/dist_mnist/trainer/config.json | refactor, same behavior
created | lib/python/flame/examples/hybrid/\__init\__.py | 
created | lib/python/flame/examples/hybrid/aggregator/\__init\__.py | 
created | lib/python/flame/examples/hybrid/aggregator/config.json | example config
created | lib/python/flame/examples/hybrid/trainer/\__init\__.py | 
created | lib/python/flame/examples/hybrid/trainer/config_eu_german.json | example config
created | lib/python/flame/examples/hybrid/trainer/config_eu_uk.json | example config
created | …
> feature: hybrid mode

- fiab/helm-chart/templates/mosquitto2-deployment.yaml
- fiab/helm-chart/templates/mosquitto2-service.yaml
- lib/python/flame/backend/mqtt.py
- lib/python/flame/channel_manager.py
- lib/python/flame/config.py
- lib/python/flame/examples/hybrid/trainer/config_us_west.json
- lib/python/flame/examples/hybrid/trainer/main.py
Each channel can have its own backend instead of using a single
backend. This allows per-channel optimization.
> feature: per-channel backend support

- docs/02-getting-started.md
since only macOS setup was available.
> prerequisite setup for ubuntu

- examples/distributed_training/dataset_1.json
- examples/distributed_training/dataset_2.json
- examples/distributed_training/dataset_3.json
- lib/python/flame/examples/hybrid/aggregator/config.json
- lib/python/flame/examples/hybrid/trainer/config_eu_org1.json
- lib/python/flame/examples/hybrid/trainer/config_eu_org2.json
- lib/python/flame/examples/hybrid/trainer/config_us_org1.json
- lib/python/flame/examples/hybrid/trainer/config_us_org2.json
- lib/python/flame/mode/distributed/trainer.py
- lib/python/flame/mode/hybrid/trainer.py
Hybrid mode of combining distributed learning and federated learning
is implemented. This implementation is based on PR #131.
The current implementation has a bug thta can cause a deadlock when
trainers arrive late. Addressing the issue will be handled as a
separate PR as it requires quite changes in backend, channel, channel
manager, etc.
> feature: hybrid mode with ring allreduce

- cmd/deployer/app/appserver.go
- cmd/deployer/app/service.go
- cmd/deployer/cmd/root.go
- cmd/deployer/main.go
- fiab/helm-chart/templates/apiserver-ingress.yaml
- fiab/helm-chart/templates/controller-job-configmap.yaml
- fiab/helm-chart/templates/deployer-deployment.yaml
- fiab/helm-chart/templates/mlflow-ingress.yaml
- fiab/helm-chart/templates/notifier-ingress.yaml
Several files that are recently added don't have license statements.
license statements are added in those files.
> misc: add missing license

- fiab/flame.sh
if "flame.sh stop" is executed more than once, the current script
destroys configuration of coredns. As a resolution, we delete last 5
lines of the config if a flame.test section exists in coredns config.
> harden flame.sh stop process

- api/computes_api.partials.yml
- api/computes_components.partials.yml
- api/computes_securityschemes.partials.yml
- api/openapi.yaml.mustache
- pkg/openapi/api.go
- pkg/openapi/api_computes.go
- pkg/openapi/apiserver/api_computes_service.go
- pkg/openapi/controller/api_computes_service.go
- pkg/openapi/model_agent_state.go
- pkg/restapi/restapi.go
This pr adds apiKey parameter to deployer restAPIs. It is the first step towards authenticating the deployers while they add or revoke resources for deployments.
> Adding apikey to deployer apis

- cmd/controller/app/database/mongodb/helpers.go
- cmd/controller/app/deployer/docker.go
- cmd/flamelet/app/taskhandler.go
- pkg/openapi/impl.go
- pkg/restapi/restapi.go
- pkg/util/helpers.go
Ran gofmt for all files as linter picks up some issues with version 1.48.0
> Minor formatting updates

- lib/python/flame/backend/p2p.py
python grpc server doesn't have an easy way to check whether a
client is dropped or not. This makes it hard to manage endpoint in
the flame channel concept and hence can cause deadlock situations
where an endpoint (working as grpc server) waits for data to arrive
from an endpoint which is dropped.
As a workaround, a heart beat is sent periodically; if it is not
received for a certain duration, it is assumed that the client is
dropped. The grpc server cleans up resources allocated for the
endpoint, which prevents deadlock.
> p2p backend: heart beat

- fiab/helm-chart/control/values.yaml
This is to address https://github.com/cisco-open/flame/issues/226.
> nginx proxy-body-size update in fiab

- README.md
Support info is added in the main README file.
> Chore: Update support info

- CONTRIBUTING.md
CONTRIBUTING.md file is updated to further clarify the coding style guideline.
> Chore: update coding style in CONTRIBUTING.md

- docs/03-fiab.md
- docs/03.A-fiab-linux.md
- docs/03.B-fiab-ec2.md
- docs/03.C-fiab-mac.md
Updated Readme with instructions to set up minikube in ec2 instance and steps to enable GPU on minikube
> Installation steps for ec2 instance

- fiab/install.sh
- fiab/ubuntu.sh
added bash script to install fiab prerequisites (minikube, kubectl, helm, jq, docker) in ubuntu
> ubuntu fiab prerequisites installer

- docs/03-a-ubuntu.md
- fiab/ubuntu.sh
added information about automation script in installation document
> updated ubuntu fiab documentation

- docs/03-c-mac.md
- fiab/install.sh
- fiab/mac.sh
added automation script for installing fiab prerequisites in macos
> mac fiab prerequisites automation

- docs/03-a-ubuntu.md
- docs/03-c-mac.md
Made building flame image as an optional step on ubuntu and Macos documents
> updated fiab installation documents

- fiab/deployer.sh
- fiab/helm-chart/deployer/values.yaml
Made changes in deployer.sh to use public flame image by default
> updated deployer script to use public image

- scripts/flameDiagnose.sh
> Create diagnose script

- lib/python/flame/common/typing.py
- lib/python/flame/common/util.py
- lib/python/flame/examples/hier_mnist/middle_aggregator/config_uk.json
- lib/python/flame/examples/hier_mnist/middle_aggregator/config_us.json
- lib/python/flame/examples/hier_mnist/top_aggregator/config.json
- lib/python/flame/examples/hier_mnist/trainer/config_uk.json
- lib/python/flame/examples/hier_mnist/trainer/config_us.json
- lib/python/flame/examples/mnist/aggregator/config.json
- lib/python/flame/examples/mnist/trainer/config.json
- lib/python/flame/mode/distributed/trainer.py
- lib/python/flame/mode/horizontal/asyncfl/middle_aggregator.py
- lib/python/flame/mode/horizontal/asyncfl/top_aggregator.py
- lib/python/flame/mode/horizontal/middle_aggregator.py
- lib/python/flame/mode/horizontal/top_aggregator.py
- lib/python/flame/mode/horizontal/trainer.py
- lib/python/flame/mode/hybrid/trainer.py
- lib/python/flame/optimizer/abstract.py
- lib/python/flame/optimizer/fedavg.py
- lib/python/flame/optimizer/fedbuff.py
- lib/python/flame/optimizer/fedopt.py
- lib/python/setup.py
For asyncfl, a client (trainer) should send delta by subtracting local weights from original global weights after training. In the current implementation, the whole local weights were sent to a server (aggregator). This causes loss divergence.
Supporting delta update requires refactoring of aggregators of synchronous fl (horizontal/{top_aggregator.py, middle_aggregator.py}) as well as optimizers' do() function.
The changes here support delta update universally across all types of modes (horizontal synchronous, asynchronous, and hybrid).
> fix+refactor: asyncfl loss divergence

- lib/python/flame/examples/adult/aggregator/config.json
- lib/python/flame/examples/adult/trainer/config.json
- lib/python/flame/examples/dist_mnist/trainer/config1.json
- lib/python/flame/examples/dist_mnist/trainer/config2.json
- lib/python/flame/examples/dist_mnist/trainer/config3.json
- lib/python/flame/examples/hier_mnist/middle_aggregator/config_uk.json
- lib/python/flame/examples/hier_mnist/middle_aggregator/config_us.json
- lib/python/flame/examples/hier_mnist/top_aggregator/config.json
- lib/python/flame/examples/hier_mnist/trainer/config_uk.json
- lib/python/flame/examples/hier_mnist/trainer/config_us.json
- lib/python/flame/examples/hybrid/aggregator/config.json
- lib/python/flame/examples/hybrid/trainer/config_eu_org1.json
- lib/python/flame/examples/hybrid/trainer/config_eu_org2.json
- lib/python/flame/examples/hybrid/trainer/config_us_org1.json
- lib/python/flame/examples/hybrid/trainer/config_us_org2.json
- lib/python/flame/examples/medmnist/aggregator/config.json
- lib/python/flame/examples/medmnist/trainer/config.json
- lib/python/flame/examples/mnist/aggregator/config.json
- lib/python/flame/examples/mnist/trainer/config.json
This PR formats example config files for the flame sdk.
> Format example json configuration files

- .pre-commit-config.yaml
- lib/python/setup.py
This PR adds pre-commit support which will make sure code from different developers is formatted in the same fashion. The following hooks are installed:
- black (python formatter) with `--line-length=80` and `--skip-string-normalization` flags
- isort (import sorter) with `--profile=black` and `--line-length=80` flags
- flake8 with `--ignore=E203,W503`, `--max-complexity=10`, `--max-line-length=80` and `--select=B,C,E,F,W,T4,B9` flags
- check-yaml - checks yaml files for parseable syntax
- check-json - checks json files for parseable syntax
- end-of-file-fixer - ensures that a file is either empty, or ends with one newline
- trailing-whitespace - trims trailing whitespace
- pretty-format-json with `--no-sort-keys`, `--autofix` and `--indent=4` - sets a standard for formatting json files
- …
> Add pre commit support

- pkg/openapi/api_design_schemas.go
- pkg/openapi/api_jobs.go
Fixing duplicate code linting issue. The blocks of code are not duplicated but the structure was very similar and this triggered the linter to fail
> Fix linting issue

- lib/python/flame/channel.py
- lib/python/flame/config.py
- lib/python/flame/examples/oort_mnist/README.md
- lib/python/flame/examples/oort_mnist/__init__.py
- lib/python/flame/examples/oort_mnist/aggregator/__init__.py
- lib/python/flame/examples/oort_mnist/aggregator/main.py
- lib/python/flame/examples/oort_mnist/config/agg_template.json
- lib/python/flame/examples/oort_mnist/config/train_template.json
- lib/python/flame/examples/oort_mnist/run.py
- lib/python/flame/examples/oort_mnist/trainer/__init__.py
- lib/python/flame/examples/oort_mnist/trainer/main.py
- lib/python/flame/mode/horizontal/oort/top_aggregator.py
- lib/python/flame/mode/horizontal/oort/trainer.py
- lib/python/flame/mode/message.py
- lib/python/flame/selector/oort.py
- lib/python/flame/selectors.py
Implement a new selector based on Oort paper (Fan Lai et al., Oort: Efficient Federated Learning via Guided Participant Selec Learning via Guided Participant Selection, OSDI'21) that requires the followings:
- Statistical utility measurement on trainers during epoch 1 for each round (refer to lib/python/flame/examples/oort_mnist/trainer/main.py)
- System utility measurement on trainers from of their participating rounds (refer to lib/python/flame/mode/horizontal/oort_top_aggregator.py)
- Trainer selection based on each utility measurement (refer to lib/python/flame/selector/oort.py)
Run the example by referring to lib/python/flame/examples/oort_mnist/README.md
related …
> example/implementation for Oort

- lib/python/flame/examples/async_hier_mnist/top_aggregator/config.json
- lib/python/flame/examples/medmnist/trainer/fedadagrad/fedadagrad1.json
- lib/python/flame/examples/medmnist/trainer/fedadagrad/fedadagrad2.json
- lib/python/flame/examples/medmnist/trainer/fedadagrad/fedadagrad3.json
- lib/python/flame/examples/medmnist/trainer/fedadam/fedadam1.json
- lib/python/flame/examples/medmnist/trainer/fedadam/fedadam2.json
- lib/python/flame/examples/medmnist/trainer/fedadam/fedadam3.json
- lib/python/flame/examples/medmnist/trainer/fedavg/fedavg1.json
- lib/python/flame/examples/medmnist/trainer/fedavg/fedavg2.json
- lib/python/flame/examples/medmnist/trainer/fedavg/fedavg3.json
- lib/python/flame/examples/medmnist/trainer/fedyogi/fedyogi1.json
- lib/python/flame/examples/medmnist/trainer/fedyogi/fedyogi2.json
- lib/python/flame/examples/medmnist/trainer/fedyogi/fedyogi3.json
Add group association info to config files that did not have one (mostly
under medmnist example)
Remove comma from top_aggregator config file's group association which results in error
> fix: remove errors regarding group association to SDK config files

- README.md
Flame supports several algorithms/mechanisms. Those are listed as a table.
> doc: update supported algorithms/mechanisms

- lib/python/flame/backend/chunk_manager.py
- lib/python/flame/backend/p2p.py
Some state was not cleaned up when channel leave happens. There may be chunk manager threads for end ids in a channel. Also, sending heartbeat to meta server for the channel is unnecessary. These two cases are handled here.
> feat: additional optimization for channel leave

- lib/python/examples/dp_mnist/__init__.py
- lib/python/examples/dp_mnist/aggregator/__init__.py
- lib/python/examples/dp_mnist/aggregator/config.json
- lib/python/examples/dp_mnist/aggregator/main.py
- lib/python/examples/dp_mnist/trainer/__init__.py
- lib/python/examples/dp_mnist/trainer/config.json
- lib/python/examples/dp_mnist/trainer/main.py
- lib/python/flame/config.py
- lib/python/flame/mode/horizontal/coord_syncfl/trainer.py
- lib/python/flame/mode/horizontal/feddyn/trainer.py
- lib/python/flame/mode/horizontal/oort/trainer.py
- lib/python/flame/mode/horizontal/syncfl/trainer.py
- lib/python/flame/privacies.py
- lib/python/flame/privacy/__init__.py
- lib/python/flame/privacy/default.py
- lib/python/flame/privacy/differential_privacy.py
differential privacy for federated learning is now supported with flame, within a new category of 'privacy'. differential privacy adds gaussian noise at the delta_weights that are sent from trainers. As a common practice, noise is added after clipping and scaling the delta_weights to avoid their norm exceeding a threshold, for better privacy.
> new feature: add differential privacy

- cmd/controller/cmd/root.go
- cmd/controller/config/config.go
- cmd/deployer/app/resource_handler.go
> Test Logging

- README.md
- docs/03-a-ubuntu.md
- docs/03-b-amzn2-gpu.md
- docs/03-c-mac.md
- docs/03-fiab.md
- docs/04-examples.md
Fixed some typos in README.md and docs
> documentation: fix typos in README.md and docs

- README.md
The flame axriv paper is published on Arxiv. Hence, the citation info is updated in the ReADME file.
> doc: add citation for flame arxiv paper

- cmd/controller/app/job/builder.go
- cmd/controller/app/job/builder_test.go
- cmd/deployer/app/monitor_jobs.go
To aid debugging in deployer, add a debugging message.
> misc: add debug message in deployer

- cmd/deployer/app/deployer/k8s.go
Pod status won't be updated correctly due to timestampe check. The pod creation time won't change once it's set although the pod status can change. Therefore, checking creation time to check whether or not to decide status update prevents the correct status update. The modified code updates the status regardless of timestamp.
> fix: deployer pod state update

- fiab/helm-chart/control/values.yaml
- fiab/helm-chart/deployer/values.yaml
v0.2.3 was released. The fiab's image version is set to v0.2.3.
> misc: update image version in fiab

- lib/python/flame/mode/horizontal/coord_syncfl/trainer.py
The base syncfl's trainer introduced fetch_success boolean variable. The trainer in coordinated syncfl didn't set the boolean variable properly, which resulted in a deadlock situation. Now the variable is updated correctly.
> fix: trainer hang in coordinated syncfl

- lib/python/setup.py
The pydantic version must be <2.0 in order for the validation requirements to be met with current examples.
> fix: pydantic version specification

- README.md
- docs/00-toc.md
- docs/05-flame-basics.md
- docs/08-flame-sdk.md
- docs/quickstart-ubuntu.md
A more concise quickstart was added to the docs folder, and it is linked to the top level README file. It includes less material than the previous quickstart file.
A short discussion on how flame's sdk is organized is included in the FL basics document. This familiarizes the user with frequent vocabulary used throughout the repo and also contains some intuition about how FL systems run on flame.
> docs: quickstart and FL basics

- fiab/helm-chart/control/values.yaml
- fiab/helm-chart/deployer/values.yaml
> misc: bump fiab image version to v0.3.0

- README.md
> misc: update flame bibtex

- fiab/helm-chart/control/templates/dashboard-configmap.yaml
- fiab/helm-chart/control/templates/dashboard-deployment.yaml
- fiab/helm-chart/control/templates/dashboard-ingress.yaml
- fiab/helm-chart/control/templates/dashboard-service.yaml
- fiab/helm-chart/control/values.yaml
> Added UI yaml files

- fiab/helm-chart/control/templates/apiserver-ingress.yaml
- fiab/helm-chart/control/templates/dashboard-ingress.yaml
- fiab/helm-chart/control/templates/mlflow-ingress.yaml
- fiab/helm-chart/control/values.yaml
Added support for http for apiserver, updated annotations with no TLS name and updates usages of that.
> Added http support for apiserver.

- .gitignore
- dashboard/public/index.html
- dashboard/src/App.tsx
Added dummy react app debug request.
> Added React app debug logs.

- fiab/helm-chart/control/templates/apiserver-ingress.yaml
- fiab/helm-chart/control/templates/dashboard-configmap.yaml
- fiab/helm-chart/control/templates/dashboard-ingress.yaml
- fiab/helm-chart/control/templates/mlflow-ingress.yaml
- fiab/helm-chart/control/values.yaml
To handle CORS properly, nginx ingress configuration is updated. In addition, annotationsNoTls is removed as it is not necessary. In order to disable tls, removing tls block in ingress.yaml files is enough. Thus, the configuration is cleaned up.
> feat: handle cors

- scripts/addlicense.sh
License header needs to be added for react app. Its file extensions (js, ts and tsx) are added into addlicense.sh file.
> misc: update addlicense file for react app

- fiab/helm-chart/control/values.yaml
- fiab/helm-chart/deployer/values.yaml
The image version for fiab is updated to v0.4.0. The version contains the web-based UI application.
> misc: fiab image version to v0.4.0

- dashboard/src/features/datasets/components/dataset-list/DatasetList.tsx
- dashboard/src/hooks/useDatasets.ts
> Added edit Dataset on UI

- dashboard/src/features/design/DesignContext.ts
- dashboard/src/features/design/components/DesignFormModal.tsx
- dashboard/src/features/design/components/DesignList.tsx
- dashboard/src/features/design/hooks/useDesigns.ts
> Added edit design functionality.

- cmd/flamectl/cmd/update-dataset.go
- cmd/flamectl/resources/dataset/dataset.go
> Added update dataset functionality for flamectl.

- lib/python/flame/mode/horizontal/feddyn/trainer.py
- lib/python/flame/mode/horizontal/scaffold/top_aggregator.py
- lib/python/flame/optimizer/regularizer/feddyn.py
- lib/python/flame/optimizer/regularizer/fedprox.py
- lib/python/flame/optimizer/regularizer/scaffold.py
Formatting for all files touched on the previous PR were added. There was also one unused import in scaffold's regularizer.
> refactor: formatting on files and unused import

- lib/python/setup.py
> Upgraded mlflow version from 2.0.1 to 2.1.1

- cmd/flamectl/cmd/remove_dataset.go
- cmd/flamectl/cmd/update_design.go
- cmd/flamectl/resources/design/design.go
> Update design and delete dataset on flamectl.

- dashboard/src/features/computes/ComputesPage.tsx
- dashboard/src/features/design/components/DesignList.tsx
- dashboard/src/features/job-details/components/job-run-timeline/JobRunTimeline.tsx
- dashboard/src/features/job-details/components/metrics-timeline/MetricsTimeline.tsx
- dashboard/src/features/job-details/types.ts
- dashboard/src/features/job-details/utils.ts
- dashboard/src/features/jobs/JobPage.tsx
- dashboard/src/features/utils.ts
> Updated logic for fetching metrics.

- dashboard/src/features/design/hooks/useDesigns.ts
- dashboard/src/services/api-client.ts
> Fixed errors in useDesigns hook.

- dashboard/src/features/design-details/DesignDetailsPage.tsx
> Fixed force delete design form Design Details.

- dashboard/src/components/custom-node-no-interaction/CustomNodeNoInteraction.tsx
- dashboard/src/features/job-details/components/job-topology/JobTopology.tsx
- dashboard/src/features/job-details/components/task-logs/TaskLogs.tsx
- dashboard/src/features/job-details/utils.ts
- fiab/helm-chart/control/values.yaml
> Added fixes for logs and for local image.

- lib/python/flame/mode/composer.py
- lib/python/flame/mode/tasklet.py
Added parallel execution of tasklets.
> Added parallel execution.

- .golangci.yml
update linter configs for golangci-lint v1.58
> update linter configs

- build/Dockerfile
> Upgrade go container in Dockerfile

- README.md
contributor's account pictures are added
> chore: adding contributors

- docs/prerequisites.md
- docs/quickstart-ubuntu.md
> Updated Ubnutu version and go version in docs.
