cmd/controller/app/job/notify.go, cmd/flamelet/app/taskhandler.go
grpc.WithInsecure is deprecated. The option is replaced with
WithTransportCredentials and insecure.NewCredentials().
=> update grpc insecure option

fiab/flame.sh
Corrected the line numbers discrepancy caused by the addition of a license.
-- | -- | --
modified | fiab/flame.sh | changed line numbers
=> fix: correct flame script

build/Dockerfile
Due to package update to resolve security issues, some packages now
require golang 1.17. Hence, golang docker image version is bumped.
=> Bump golang docker image to 1.17.8-buster

lib/python/flame/optimizer/fedavg.py
The previous global weights were not reset before new global weights
are computed in each round. This caused loss value increase over
rounds. This error is fixed.
=> fix: fedavg algo

templates/job/job-agent.yaml.mustache, templates/job/values.yaml
The parameters for apiserver and notifier are not flexible as some
parts in the endpoints are hard-coded. Now users can update
values.yaml to set endpoints as they want.
=> make job agent config flexible

lib/python/flame/plugin/__init__.py
when plugin config directory (/etc/flame/plugin) doesn't exist, it
raises FileNotFoundError. since plugin is optional, it's okay to move
forward even with that exception.
=> fix: plugin registration exception

lib/python/flame/config.py, lib/python/flame/examples/dist_mnist/__init__.py, lib/python/flame/examples/dist_mnist/trainer/__init__.py, lib/python/flame/examples/dist_mnist/trainer/config.json, lib/python/flame/examples/dist_mnist/trainer/main.py, lib/python/flame/mode/distributed/__init__.py, lib/python/flame/mode/distributed/trainer.py
This is an example of distributed training with the MQTT backend. It's for demonstration purposes so It doesn't have efficient communication backends for now. This distributed training mode will work even if there is only one trainer. The newly-joined trainer will receive the latest aggregated weights before start contributing.
-- | -- | --
modified | lib/python/flame/config.py | add the number of distributed learning nodes to the configuration
modified | lib/python/flame/mode/message.py | add new message types
created | lib/python/flame/examples/dist_mnist/\__init__.py | 
created | lib/python/flame/examples/dist_mnist/trainer/\__init__.py | 
created | lib/python/flame/examples/dist_mnist/trainer/config.json | example config
created | …
=> feature: distributed training with mqtt

lib/python/flame/backend/mqtt.py, lib/python/flame/mode/horizontal/top_aggregator.py, lib/python/flame/selector/default.py
A deadlock occurs when workers join late after aggregator distributes
global parameters. This is because the aggregator will wait for local
parameters from those workers to which it didn't distribute the global
parameters. To solve the issue, the default selector remembers a set
of workers it distributed the global parameters in each round and
within the round the aggregator will try to receive local parameters
from the same set of workers.
=> fix: deadlock case in default selector

lib/python/flame/config.py, lib/python/flame/registries.py, lib/python/flame/registry/dummy.py, lib/python/flame/registry/mlflow.py
A dummy model registry client is implemented. This allows an
experiment without having a proper model registry such as mlflow.
=> feature: dummy model registry client

cmd/deployer/app/appserver.go, cmd/deployer/app/service.go, cmd/deployer/cmd/root.go, cmd/deployer/main.go, fiab/helm-chart/templates/deployer-deployment.yaml, pkg/util/constants.go
This initiates an important change for the flame controlplane. We will be developing a separate `deployer` service to de-couple the current `deployer` from `controller`. A separate `deployer` service required to add support for Flame to run across multiple clusters.
This first commit creates a separate `pod` for deployer that is perpetually in a `running` state. To enable this, a placeholder app for the deployer was created and the helm-chart files were also added. The app will be implemented in the future commits to expose all the required services for the deployer.
=> [control-plane] First commit for deployer as separate pod

fiab/Vagrantfile, fiab/bootstrap.sh, fiab/flame.sh
The private dns support under a linux fiab env is broken. It is fixed
now under Ubuntu 20.04 LTS. Testing is done using Ubuntu 20.04 LTS
under vagrant environment.
=> fix: private dns support in linux fiab env

lib/python/flame/mode/distributed/trainer.py, lib/python/flame/mode/message.py
This commit allows a new trainer to fetch the latest global weight of distributed learning. The weight can either be 1) from the global weights produced by the ring all-reduce algorithm or 2) from a single trainer if there is only one trainer previsouly. Either case the trainer that holds the current best weights will be the committer.
-- | -- | --
modified | lib/python/flame/mode/distributed/trainer.py | use existing communication channel to fetch latest weights
modified | lib/python/flame/mode/message.py |  add a new message type
=> feature: fetch latest weights in distributed learning

lib/python/flame/mode/distributed/trainer.py
This commit reduces the complexity of the distributed learning code by storing the ends who agree with the ring topology at a time, so that a trainer in a ring won't send weights message to trainers outside of the ring. Meanwhile, a new trainer's arrival message won't send to the trainers in a ring either. Hence, the moment that a new trainer fetches the global optimal weights will be when the new trainer is in the ring.
-- | -- | --
modified | lib/python/flame/mode/distributed/trainer.py | store ends in a ring separately
=> optimize: reduce distributed learning code complexity

fiab/helm-chart/Chart.yaml, fiab/helm-chart/job/job-agent.yaml.mustache, fiab/helm-chart/templates/controller-job-configmap.yaml, fiab/helm-chart/templates/mlflow-deployment.yaml, fiab/helm-chart/templates/mlflow-ingress.yaml, fiab/helm-chart/templates/mlflow-service.yaml, fiab/helm-chart/values.yaml
In fiab, mlflow is configured without an object store. Therefore,
artifacts (e.g., model) are stored locally within a container. Once
training is over, then the artifacts get lost. With support for
minio (an open-source object store), now artifacts are saved in an
object store. Also, minio's endpoint is exposed via ingress so that
workers outside a cluster can save artifacts. Note that tls for minio
is not enabled because selfsigned cert used in fiab is likely to make
mlflow's client complain about a verification issue.
A caveat is that no persistent volume is configured in this minio
setup, artifacts will get lost if minio pod crashes or terminates. The
support for minio is for reference so that users can configure minio
or aws s3 correctly for production.
=> feature: minio support in fiab

examples/distributed_training/schema.json
Previously, the distributed learning topology works with python library but doesn't work with flame system. It turns out to be a simple typo error. Now fixed.
-- | -- | --
modified | examples/distributed_training/schema.json | update func tags in schema
=> typo: use correct func tags for distributed learning

lib/python/flame/examples/dist_mnist/trainer/config1.json, lib/python/flame/examples/dist_mnist/trainer/config2.json, lib/python/flame/examples/dist_mnist/trainer/config3.json, lib/python/flame/mode/distributed/trainer.py
During the member check, there is a high chance to receive weights
message because other workers started ring all-reduce process while
a trainer is in a member check loop. In such a case, the current code
will delcare failure of the membership check. This creates an
inconsistent agreement among workers, meaning that some think they are
in a ring and some others don't. To address the issue, we reinstate
the peek statement.
In addition, some cosmetric reformatting is done.
=> fix: message mixed up in distributed learning mode

docs/03-fiab.md
If not used, minikube start doesn't work after minikube delete.
=> Making docker driver default.

api/computes_api.partials.yml, api/computes_components.partials.yml, cmd/controller/app/controller.go, cmd/controller/app/database/db_interfaces.go, cmd/controller/app/database/mongodb/compute.go, cmd/deployer/app/register.go, cmd/deployer/cmd/root.go, cmd/deployer/cmd/root_test.go, cmd/deployer/main.go, fiab/helm-chart/templates/deployer-deployment.yaml, pkg/openapi/api.go, pkg/openapi/api_computes.go, pkg/openapi/apiserver/api_computes_service.go, pkg/openapi/controller/api_computes_service.go, pkg/openapi/model_compute_spec.go, pkg/openapi/model_compute_status.go, pkg/restapi/restapi.go
Includes functionality to register new compute cluster in flame. Since the mongodb implementation for compute registration is incomplete, this is a partial pr and does not include controller implementation for compute cluster registration.
=> Initial implementation for deployer registration

cmd/deployer/app/register.go, cmd/deployer/app/resourcehandler.go, cmd/deployer/cmd/root.go, fiab/helm-chart/templates/deployer-deployment.yaml
This PR creates a grpc connection between the deployer and notifier. The connection will later be used to send events.
=> Establishing deployer notifier connection

lib/python/flame/README.md, lib/python/flame/examples/mnist/aggregator/config.json, lib/python/flame/examples/mnist/trainer/config.json
Add a README file to illustrate how one can run python library manually without engaging with the control plane.
-- | -- | --
added | lib/python/flame/README.md | a tutorial
modified | lib/python/flame/examples/mnist/aggregator/config.json | indent
modified | lib/python/flame/examples/mnist/trainer/config.json | indent
=> docs: run python library solely

cmd/controller/app/job/default_handler.go, cmd/controller/app/job/job_state.go, cmd/controller/app/job/notify.go, cmd/deployer/app/resource_handler.go, cmd/notifier/app/eventroute.go, cmd/notifier/app/server.go, cmd/notifier/app/triggerroute.go
This PR implements the eventroute and triggerroute code for notifier to receive and send deployment events. The controller triggers an add resource event while allocating computes and this event is received at the deployer.
=> Initial end-to-end pipeline for deployer

cmd/deployer/app/resource_handler.go, pkg/openapi/apiserver/api_computes_service.go, pkg/openapi/controller/api_computes_service.go
This commit establishes the deployer apiserver and controller pipeline to get deployment configuration and allocate resources.
=> Implement basic pipeline for deployer

cmd/controller/app/controller.go, cmd/controller/app/database/db_interfaces.go, cmd/controller/app/database/mongodb/job.go, cmd/deployer/app/resource_handler.go, pkg/openapi/apiserver/api_computes_service.go, pkg/openapi/controller/api_computes_service.go, pkg/util/constants.go
This pr enables the controller to correctly populate the deployment configuration for tasks to be deployed on resources. The deployer receives back this configuration which it will use to allocate new compute resources.
=> Populating deployment config for deployer

api/dataset_components.partials.yml, cmd/controller/app/database/db_interfaces.go, cmd/controller/app/database/mongodb/compute.go, cmd/controller/app/database/mongodb/task.go, cmd/controller/app/job/builder.go, cmd/controller/app/job/builder_test.go, cmd/controller/app/objects/task.go, fiab/helm-chart/values.yaml, pkg/openapi/controller/api_datasets_service.go, pkg/openapi/model_dataset_info.go, pkg/util/constants.go
This pr maps the realm in the input dataset json to the registered computes. The realm in the dataset json specifies either region OR computeId. If the dataset is private, the specified region or computeId must be correct. If it is invalid, an error would be thrown and creation of the dataset would fail. In the case of public datasets, if the region or computeId does not match, the defaultRealm is selected which also specifies a default computeId. The dataset realm is used at the time of task creation to assign computeIds and the job tasks get assigned to that compute cluster.
=> Added checks for dataset registration

fiab/helm-chart/templates/deployer-compute1-deployment.yaml, fiab/helm-chart/templates/deployer-default-deployment.yaml, fiab/helm-chart/values.yaml
This pr adds a default compute deployer besides the existing custom deployer. The default compute is primarily useful for aggregation tasks and/or running tasks on public datasets which were not correctly mapped to a compute region.
=> Added deployer for default compute

api/job_components.partials.yml, cmd/controller/app/job/default_handler.go, cmd/notifier/app/eventroute.go, cmd/notifier/app/triggerroute.go, pkg/openapi/controller/api_computes_service.go, pkg/openapi/model_task_info.go
A job consists of several tasks that might be deployed across different compute clusters. This pr allows the controller to automatically identify and notify a list of computes for deploying resources for tasks.
=> Automated deployment notification to computes

cmd/controller/app/job/default_handler.go, cmd/deployer/app/deployer/deployer.go, cmd/deployer/app/deployer/docker.go, cmd/deployer/app/deployer/k8s.go, cmd/deployer/app/resource_handler.go, fiab/helm-chart/templates/deployer-compute1-deployment.yaml, fiab/helm-chart/templates/deployer-default-deployment.yaml, fiab/helm-chart/templates/deployer-job-configmap.yaml
This pr is a step towards implementing the core deployment logic into the deployer. We duplicate the relevant code and logic from the controller's deployer and put it as placeholder in the standalone deployer's code. At a later stage, only logic within the deployer will remain and all deployment related code from the controller will be removed.
=> Duplicating controllers deployment code into deployer

fiab/helm-chart/templates/deployer-compute1-deployment.yaml, fiab/helm-chart/templates/deployer-default-deployment.yaml, fiab/helm-chart/templates/deployer-role-and-rolebinding.yaml, fiab/helm-chart/templates/deployer-service-account.yaml
This pr adds service account, roles and role bindings for deployer. These privileges will be used by the deployer to create and delete pods for tasks.
=> Added servAcc and roleBinding for deployer

cmd/controller/app/job/builder.go, cmd/deployer/app/resource_handler.go, cmd/flamectl/resources/code/code.go, cmd/flamectl/resources/dataset/dataset.go, cmd/flamectl/resources/job/job.go, cmd/flamectl/resources/schema/schema.go, cmd/flamelet/app/taskhandler.go, pkg/openapi/routers.go, pkg/restapi/restapi.go, pkg/util/zip.go
The golang linter complained that io-ioutil is deprecated. Thus the function calls were replaced with relevant io and os package APIs.
=> Removed deprecated io-ioutil API calls

api/computes_components.partials.yml, cmd/deployer/app/resource_handler.go, pkg/openapi/controller/api_computes_service.go, pkg/openapi/model_deployment_config.go
This pr updates the agentKV field of deployementConfig spec to a simple map instead of a list of maps.
=> Updated spec for deploymentConfig

cmd/controller/app/job/default_handler.go, cmd/controller/app/job/notify.go, cmd/deployer/app/resource_handler.go, cmd/notifier/app/triggerroute.go
This pr adds initial error handling for the deployer. Failures at the controller while sending events to the deployer and at the deployer while adding or revoking resources can be handled. Propagating the error back from deployer to controller will be a part of another pr.
=> Initial error handling for deployer

cmd/controller/app/database/mongodb/job.go
This is a bug fix for the fetching correct set of tasks for a job when the requesting client is a deployer.
=> Bug fix for deployment of tasks

lib/python/flame/backend/p2p.py
There is a message limit in gRPC. The default value is about 4MB defined in GRPC_DEFAULT_MAX_RECV_MESSAGE_LENGTH in grpc_types.h from grpc source code.
This limitation creates ExecuteBatchError or returns an error status code such as StatusCode.RESOURCE_EXHAUSTED.
In order to mitigate the issue, 'grpc.max_send_message_length' and 'grpc.max_receive_message_length' in both client and server are increased to 1GB.
=> grpc max message length update

lib/python/flame/backend/chunk_store.py, lib/python/flame/backend/mqtt.py, lib/python/flame/backend/p2p.py, lib/python/flame/channel.py, lib/python/flame/channel_manager.py, lib/python/flame/common/constants.py, lib/python/flame/mode/horizontal/middle_aggregator.py, lib/python/flame/mode/horizontal/top_aggregator.py, lib/python/flame/mode/horizontal/trainer.py, lib/python/setup.py
The flame library presents some inefficiency.
1) In order to check if there is at least one peer in a channel, it busy-waits by calling empty() function and sleep one second.
2) head-of-line blocking problem: to recv data from peers of a channel, the implementation gets the list of peers, loops through each of peers and calls recv(). If the first peer is a straggler, it causes a head-of-line blocking problem.
3) When model size increases, it takes a while to merge transmitted messages (it is byte array concatenation operation). This process takes place in a coroutine; and it isn't suspended until it is finished. This delays a heart beat transmission as the heart beat function is also a coroutine. The delayed heart beat triggers a timeout at the other side of grpc channel, which breaks a …
=> event driven approach

api/design_api.partials.yml, pkg/openapi/api.go, pkg/openapi/api_design_codes.go, pkg/openapi/apiserver/api_design_codes_service.go, pkg/openapi/controller/api_design_codes_service.go
added boiler plate code for the delete code in api endpoints
=> delete code api endpoint

docs/02-getting-started.md, fiab/Vagrantfile
The current documentation on Linux part is outdated. The updated document is tested under a vagrant environment with Ubuntu 20.04 image from https://app.vagrantup.com/ubuntu/boxes/focal64.
=> Update setup guideline for Ubuntu 20.04

cmd/controller/app/database/db_interfaces.go, cmd/controller/app/database/mongodb/code.go, cmd/controller/app/database/mongodb/code_test.go, cmd/controller/cmd/root.go, cmd/flamectl/cmd/delete_code.go, cmd/flamectl/resources/code/code.go, pkg/openapi/apiserver/api_design_codes_service.go, pkg/openapi/controller/api_design_codes_service.go, pkg/restapi/restapi.go, pkg/util/constants.go
Added code to flamectl cli to Support remove command.
Added code to process remove command Http request on Api server and controller.
Added code to update DB , when a code is removed.
=> delete design code

lib/python/flame/examples/medmnist/aggregator/config.json, lib/python/flame/examples/medmnist/trainer/config.json, lib/python/flame/mode/horizontal/middle_aggregator.py, lib/python/flame/mode/hybrid/trainer.py
Fixed a typo in the skeleton code of middle aggregator; fixed a logic error in hybrid skeleton code as a message can contain more than one type of content; updated config file for MedMNIST for latest version of flame.
-- | -- | --
modified | lib/python/flame/mode/horizontal/middle_aggregator.py | fatal typo
modified | lib/python/flame/mode/hybrid/trainer.py | if/else statement logic error
modified | lib/python/flame/examples/medmnist/aggregator/config.json | remove mlflow
modified | lib/python/flame/examples/medmnist/aggregator/config.json | remove mlflow
=> fix: typo and logic error

cmd/controller/app/database/db_interfaces.go, cmd/controller/app/database/mongodb/schema.go, cmd/controller/app/database/mongodb/schema_test.go, cmd/flamectl/cmd/delete_schema.go, cmd/flamectl/resources/code/code.go, cmd/flamectl/resources/schema/schema.go, pkg/openapi/apiserver/api_design_schemas_service.go, pkg/openapi/controller/api_design_codes_service.go, pkg/openapi/controller/api_design_schemas_service.go, pkg/restapi/restapi.go, pkg/util/constants.go
Test Summary:
```
vagrant@flame:/flame/examples/mnist$ flamectl get schemas -d mnist --insecure
Warning: --insecure flag is set; allow insecure connection.
[
{
"version": "1",
"name": "A simple example schema v1.0.0",
"description": "a sample schema to demostrate a TAG layout",
"roles": [
{
"name": "trainer",
"description": "It consumes the data and trains local model",
"isDataConsumer": true
},
{
"name": "aggregator",
"description": "It aggregates the updates from trainers",
"replica": 1
}
],
"channels": [
{
"name": "param-channel",
"description": "Model update is sent from trainer to aggregator and vice-versa",
"pair": [
"trainer",
"aggregator"
],
"groupBy": {
"type": "tag",
"value": [
"default/us"
]
},
"funcTags": {
"aggregator": [
"distribute",
"aggregate"
],
"trainer": [
"fetch", …
```
=> Add mongo document deletion for delete schema

lib/python/flame/channel.py, lib/python/flame/mode/composer.py, lib/python/flame/mode/horizontal/middle_aggregator.py, lib/python/flame/mode/horizontal/top_aggregator.py, lib/python/flame/mode/tasklet.py, lib/python/setup.py
We add 'continue' primitive in the tasklet code of the flame library. The 'continue' primitive is used to move back to the start of loop when a certain condition is met. A condition is defined as a function, which will be set via set_continue_fn member function.
As an example use case of 'continue' primitive, a middle aggregator code is extended in the following way: If no trainer join a channel that the middle aggregator is waiting on for a minute, the middle aggregator gives up waiting and updates the top aggregator with dummy weights so that the top aggregator can be unblocked. Then, the middle aggregator goes back to the start of the loop so that it can retrieve model weights of a new global model from the top aggregator.
=> feat: 'continue' primitive in tasklet

lib/python/flame/registry/mlflow.py, lib/python/setup.py
In mlflow 2.0 or above, keras is not provided as a separate module. Instead, tensorflow module is used. When mlflow.keras is imported, mlflow.tensorflow is simply imported. So, trying to do getattr with string "keras" fails because there is no module called keras.
To fix the issue, when keras is identified, we use tensorflow flavor and call getattr with "tensorflow".
=> fix: mlflow flavor "keras" not found

fiab/build-image.sh, fiab/flame.sh, fiab/helm-chart/control/values.yaml
Add args to start command for flame shell script to replace the tag name inside helmchart values file
=> Add --local-img flag to the shell script to use dev tag for local testing

fiab/setup.sh
This is a skeleton script to automate minikube configuration for fiab on different operating systems and linux distributions. Mac Os, Ubuntu and Amazon linux 2 will be supported in this automated script. Note that users can manually configure minikube on different linux distributions. The support for other linux distributions will be planned in the future.
=> chore: a skeleton script to configure minikube

api/computes_components.partials.yml, cmd/controller/app/database/mongodb/compute.go, cmd/deployer/cmd/root.go, examples/sample_experiment/deployer_config.json, pkg/openapi/model_compute_spec.go
Region is now called Realm. It is an array of tags used to describe geo-domain of the underlying cluster managed by the deployer. Additionally, a property attribute is added which will be used in the future to provide cluster properties such as GPU/TPU, storage information etc.. Such properties will be used by the ML developer to provide fine-grain specifications about the resources required to run their job.
=> Deployer Registration Changes

fiab/flame.sh, fiab/install.sh
In the script, crictl is installed in /usr/local/bin. However, when minikube is executed with sudo, minikube fails to findcrictl. The path needs to be enabled either sudoer's configuration or in root's path, each of which may not be ideal. As a workaround, a symbolic link is created under /usr/bin.
Also, during the testing, flame.sh has a bug of failing to run jq correctly when ./flame.sh stop is executed. This is because the jq's verions is < 1.6. The fix (adding '.') was applied.
=> fix: installation script for amzn2

README.md
A badge for flame slack channel is added in the README.md file.
=> chore: add badge for flame slack channel

fiab/helm-chart/control/Chart.yaml
The current version of helm chart for mongodb was removed from bitnami. A version (13.6.2) for the chart is bumped up.
=> misc: bump up mongodb chart version in fiab

docs/03-b-amzn2-gpu.md, fiab/helm-chart/control/job/job-agent.yaml.mustache, fiab/helm-chart/deployer/job/job-agent.yaml.mustache
The job template is updated to prefer a node with gpu. If gpu is not available, other nodes are considered for scheduling.
=> conf: update for gpu in job template

build/Dockerfile, fiab/flame.sh
The base image used to build a flame is changed from a cpu version to a cuda 11.3 version. While this increases an image size significantly, it allows users to use gpu-enabled flame image directly without need for them to build one on their own.
=> misc: base image update

README.md
The flame slack workspace link was expired. A new link with no expiration date is created and updated.
=> misc: fix flame slack workspace link error

docs/03-a-ubuntu.md, docs/03-b-amzn2-gpu.md, docs/03-c-mac.md
The fiab guide is outdated and incorrect. The system requirement for the env is updated. A note on command "minikube delete " was misplaced, thus causing confusion. The location of the note is updated. Finally, an image pull from minikube may fail due to a timeout (the default timeout value of 2 minutes, which is hard to change). A workaround for the problem is documented.
=> doc: fiab guide revision

README.md, docs/03-a-ubuntu.md, docs/03-b-amzn2-gpu.md, docs/03-c-mac.md, docs/04-examples.md
The workaround for the image pull timeout issue is placed in a wrong section, which makes it hard for users to apply the workaround. The instructions were refactored for better readability.
=> doc: refactor fiab instructions

cmd/controller/app/database/mongodb/code_test.go, cmd/controller/app/database/mongodb/compute_test.go, cmd/controller/app/database/mongodb/design_test.go, cmd/controller/app/database/mongodb/schema_test.go, scripts/license_header.txt
A few source files are missing the license header. The license header is added to them. And also year has been updated.
=> misc: add license header

api/design_components.partials.yml, cmd/controller/app/job/builder.go, cmd/controller/app/objects/task.go, examples/adult/schema.json, examples/distributed_training/schema.json, examples/hier_mnist/schema.json, examples/medmnist/schema.json, examples/mnist/schema.json, examples/mnist_non_orchestration_mode/schema.json, examples/parallel_experiment/schema.json, pkg/openapi/model_role.go
With this PR we are adding group association for roles in order to define to which channel and group is associated with.
=> Add group associations to roles

docs/08-flame-sdk.md, lib/python/flame/examples/mnist/aggregator/config.json, lib/python/flame/examples/mnist/trainer/config.json
Documentation for using metaserver will allow users to run examples with a local broker. This decreases the chances of any job ID collisions.
Modifications to the config.json for the mnist example were made in order to make it easier to switch to a local broker. The readme does indicate how to do this for other examples now.
=> documenation for metaserver

lib/python/flame/optimizer/fedavg.py, lib/python/flame/optimizer/fedbuff.py
Model architectures can have integer tensors. Applying aggregation on those tensors results in type mistmatch and throws a runtime error: "RuntimeError: result type Float can't be cast to the desired output type Long"
Integer tensors don't matter in back propagation. So, as a workaround to the issue, we typecast to the original dtype when the original type is different from the dtype of weighted tensors for aggregation. In this way, we can keep the model architecture as is.
=> fix: conflict bewtween integer tensor and float tensor

lib/python/flame/examples/hybrid/aggregator/config.json, lib/python/flame/examples/hybrid/trainer/config_eu_org1.json, lib/python/flame/examples/hybrid/trainer/config_eu_org2.json, lib/python/flame/examples/hybrid/trainer/config_us_org1.json, lib/python/flame/examples/hybrid/trainer/config_us_org2.json
To enable library-only execution for hybrid example, its configuration files are updated accordingly. The revised configuration has local mqtt and p2p broker config and p2p broker is selected.
=> refactor: config for hybrid example in library

lib/python/flame/examples/hybrid/aggregator/config.json, lib/python/flame/examples/hybrid/trainer/config_eu_org1.json, lib/python/flame/examples/hybrid/trainer/config_eu_org2.json, lib/python/flame/examples/hybrid/trainer/config_us_org1.json, lib/python/flame/examples/hybrid/trainer/config_us_org2.json
Due to https://github.com/grpc/grpc/issues/25364, when two p2p backends (which rely on grpc and asyncio) are defined, the hybrid mode example throws an execption: 'BlockingIOError: [Errno 35] Resource temporarily unavailable'. The issue still appears unresolved. As a temporary workaround, we use two different types of backends: mqtt for one and p2p for the other. This means that when this example is executed, both metaserver and a mqtt broker (e.g., mosquitto) must be running in the local machine.
=> fix: workaround for hybrid mode with two p2p backends

lib/python/flame/examples/dist_mnist/trainer/config1.json, lib/python/flame/examples/dist_mnist/trainer/config2.json, lib/python/flame/examples/dist_mnist/trainer/config3.json, lib/python/flame/mode/distributed/trainer.py
Distributed mode has a bug: before 'weights' is not defined as member variable, deepcopy(self.weights) in _update_weights() is called. To address this issue, self.weights is initialized in __init__().
Also, to run a distributed example locally, configuration files are revised.
=> fix: distributed mode

cmd/deployer/app/resource_handler.go, cmd/deployer/cmd/root.go, cmd/deployer/config/config.go, fiab/flame.sh, fiab/helm-chart/control/templates/deployer-configmap.yaml, fiab/helm-chart/control/templates/deployer-default-deployment.yaml, fiab/helm-chart/control/values.yaml, fiab/helm-chart/deployer/templates/deployer-compute1-deployment.yaml, fiab/helm-chart/deployer/templates/deployer-configmap.yaml, fiab/helm-chart/deployer/values.yaml, lib/python/flame/optimizer/regularizer/default.py, lib/python/flame/optimizer/regularizer/fedprox.py
deployer's job template file is hard-coded, which makes it hard to use different template file at deployment time. Using different different template file is useful when underlying infrastructure is different (e.g., k8s vs knative). To support that, template folder and file is fed as config variables.
Also, deployer's config info is fed as command argument, which is cumbersome. So, the config parsing part is refactored such that the info is fed as a configuration file.
During the testing of deployer change, a bug in the library is identified. The fix for it is added here too.
Finally, the local dns configuration in flame.sh is updated so that it can be done correctly across different linux distributions (e.g., archlinux and ubuntu). The tests for flame.sh are under archlinux and ubuntu.
=> refactor+fix: configurable deployer / lib regularizer fix

lib/python/flame/backend/chunk_manager.py, lib/python/flame/backend/chunk_store.py, lib/python/flame/backend/mqtt.py, lib/python/flame/backend/p2p.py, lib/python/setup.py
In order to minimize the blocking of asynchronous I/O tasks when a large number of message chunks (e.g., model size is large) need to be assembled, threading is used. This led to a bug wherein messages are delivered to a receive queue in an out-of-order fashion. For example, consider two back-to-back messages; the first message is larger than the second. In this case, the second can be inserted before the first because the second has high chance to finish the assembling.
The changes here are for fixing the bug. To do so, we leverage another queue to synchronize message delivery order. For that, chunk manager class is introduced. One chunk manager is created for a backend. And it maintains a list of chunk threads per end, each of which is responsible for assemling messages sequentially and …
=> fix: out of order message delivery

lib/python/flame/config.py, lib/python/flame/examples/adult/aggregator/main.py, lib/python/flame/examples/adult/trainer/main.py, lib/python/flame/examples/dist_mnist/trainer/keras/main.py, lib/python/flame/examples/dist_mnist/trainer/pytorch/main.py, lib/python/flame/examples/hier_mnist/middle_aggregator/main.py, lib/python/flame/examples/hier_mnist/top_aggregator/main.py, lib/python/flame/examples/hier_mnist/trainer/main.py, lib/python/flame/examples/hybrid/aggregator/main.py, lib/python/flame/examples/hybrid/trainer/main.py, lib/python/flame/examples/medmnist/aggregator/main.py, lib/python/flame/examples/medmnist/trainer/main.py, lib/python/flame/examples/mnist/aggregator/keras/main.py, lib/python/flame/examples/mnist/aggregator/pytorch/main.py, lib/python/flame/examples/mnist/trainer/keras/main.py, lib/python/flame/examples/mnist/trainer/pytorch/main.py
This PR brings backwards compatibility for old SDK versions.
SDK config handling was changed in https://github.com/cisco-open/flame/pull/332 which introduced a breaking change since the way config loaded has changed. This PR addresses that and "reverts" the way config is loaded back to the old way, while retaining all the benefits of pydantic.
This backwards compatibility issue was raised during testing when we figured out that the zipped examples contained old sdk config loading which did not work with SDK v0.1.0.
=> Make SDK config backwards compatible

.golangci.yml, scripts/runMinikube.sh
=> Create a run minikube script

lib/python/flame/common/util.py
The download function can take in the config's dataset field and return the location of the file where its stored (or downloaded, if that's needed). This makes it easier to load files in aggregator/main.py and trainer/main.py.
=> add download file function

lib/python/flame/channel.py, lib/python/flame/examples/oort_mnist/trainer/main.py, lib/python/flame/mode/horizontal/oort/top_aggregator.py, lib/python/flame/mode/horizontal/oort/trainer.py
The Oort algorithm performs overcommitment in trainer selection, that it selects 1.3 * K trainers at a round where K is the desired number of trainers. At the aggregation phase, the algorithm only accepts K trainers' model update in order of the arrival.
Implement the above functionality by replacing self.tmpq with self._rx_queue at channel.py in python library, which consistently gets input from end.get(). Also, channel.py now has self._active_recv_fifo_tasks, which maintains the ids of ends which are called for recv_fifo but are not finished with receiving the message.
Minor update: to comply with other functions that control trainer's utility, update lib/python/flame/examples/oort_mnist/trainer/main.py to use reset_stat_utility function instead of set_stat_utility function to make it …
=> update for Oort: overcommitment support

lib/python/flame/examples/hier_mnist/middle_aggregator/config_uk.json, lib/python/flame/examples/hier_mnist/middle_aggregator/config_us.json, lib/python/flame/examples/hier_mnist/trainer/config_uk.json, lib/python/flame/examples/hier_mnist/trainer/config_us.json, lib/python/flame/mode/horizontal/middle_aggregator.py
In a hierarchical topology, detla weights computation is not applied in the middle aggregator, which causes loss to increase over rounds. That missing code is applied.
In addition, in the configs for the hier mnist example, groupAssociation values are incorrectly set, which is now fixed.
=> fix: missing delta weights computation in middle aggregator

lib/python/flame/examples/async_hier_mnist/middle_aggregator/config_uk.json, lib/python/flame/examples/async_hier_mnist/middle_aggregator/config_us.json, lib/python/flame/examples/async_hier_mnist/trainer/config_uk1.json, lib/python/flame/examples/async_hier_mnist/trainer/config_uk2.json, lib/python/flame/examples/async_hier_mnist/trainer/config_us1.json, lib/python/flame/examples/async_hier_mnist/trainer/config_us2.json, lib/python/flame/examples/hybrid/trainer/config_eu_org1.json, lib/python/flame/examples/hybrid/trainer/config_eu_org2.json, lib/python/flame/examples/hybrid/trainer/config_us_org1.json, lib/python/flame/examples/hybrid/trainer/config_us_org2.json
In the examples of hybrid fl and hierarchical asynchronous fl, groupAssociation values are incorrectly specified. Hence, these examples didn't work.
The groups in the configs are simplified and groupAssociation values are correctly updated.
=> fix: incorrect groupAssociation in lib example configs

lib/python/flame/config.py, lib/python/flame/examples/coord_hier_syncfl_mnist/__init__.py, lib/python/flame/examples/coord_hier_syncfl_mnist/coordinator/__init__.py, lib/python/flame/examples/coord_hier_syncfl_mnist/coordinator/config.json, lib/python/flame/examples/coord_hier_syncfl_mnist/coordinator/main.py, lib/python/flame/examples/coord_hier_syncfl_mnist/middle_aggregator/__init__.py, lib/python/flame/examples/coord_hier_syncfl_mnist/middle_aggregator/config1.json, lib/python/flame/examples/coord_hier_syncfl_mnist/middle_aggregator/config2.json, lib/python/flame/examples/coord_hier_syncfl_mnist/middle_aggregator/main.py, lib/python/flame/examples/coord_hier_syncfl_mnist/top_aggregator/__init__.py, lib/python/flame/examples/coord_hier_syncfl_mnist/top_aggregator/config.json, lib/python/flame/examples/coord_hier_syncfl_mnist/top_aggregator/main.py, lib/python/flame/examples/coord_hier_syncfl_mnist/trainer/__init__.py, lib/python/flame/examples/coord_hier_syncfl_mnist/trainer/config1.json, lib/python/flame/examples/coord_hier_syncfl_mnist/trainer/config2.json, lib/python/flame/examples/coord_hier_syncfl_mnist/trainer/main.py, lib/python/flame/mode/horizontal/coord_syncfl/__init__.py, lib/python/flame/mode/horizontal/coord_syncfl/config_examples/config-mid-aggregator.json, lib/python/flame/mode/horizontal/coord_syncfl/config_examples/config-selector.json, lib/python/flame/mode/horizontal/coord_syncfl/config_examples/config-top-aggregator.json, lib/python/flame/mode/horizontal/coord_syncfl/config_examples/config-trainer.json, lib/python/flame/mode/horizontal/coord_syncfl/coordinator.py, lib/python/flame/mode/horizontal/coord_syncfl/middle_aggregator.py, lib/python/flame/mode/horizontal/coord_syncfl/top_aggregator.py, lib/python/flame/mode/horizontal/coord_syncfl/trainer.py, lib/python/flame/mode/message.py
Synchronous orchestrator architecture for Flame
Additions:
- New mode added: coord_syncfl
The new mode revolves around the new component - Coordinator.
- Top aggregator notifies the Coordinator of training state state/finish.
- Mid aggregators now consult the Coordinator for selected trainers.
- Trainers now register themselves with the Coordinator.
- New component added: Coordinator
Coordinators role is to coordinate the training process. It is responsible for selecting the trainers and aggregators and sending the selected trainers to the aggregators.
New architecture implements top and middle aggregators as well as trainers with additional lifespan steps which accomodate the protocol between them and the Coordinator.
- New example added: coord_hier_syncfl
=> Synchronous orchestrator architecture

lib/python/flame/backend/mqtt.py, lib/python/flame/channel_manager.py, lib/python/flame/config.py
The following three files are revised for a future PR: mqtt.py, channel_manager.py and config.py. As a prep, these files are auto-formatted with black.
=> refactor: auto-formatting sdk files with black

lib/python/flame/mode/hybrid/trainer.py
remove _update_weights() call from _upload_weights() function before calculating the delta weights, as such a function call makes self.prev_weights and self.weights equal, resulting in delta_weights to be all zero
=> fix: zero weight upload from trainer in hybrid mode

lib/python/flame/mode/composer.py, lib/python/flame/mode/distributed/trainer.py, lib/python/flame/mode/horizontal/asyncfl/middle_aggregator.py, lib/python/flame/mode/horizontal/asyncfl/top_aggregator.py, lib/python/flame/mode/horizontal/coord_syncfl/coordinator.py, lib/python/flame/mode/horizontal/coord_syncfl/middle_aggregator.py, lib/python/flame/mode/horizontal/coord_syncfl/top_aggregator.py, lib/python/flame/mode/horizontal/coord_syncfl/trainer.py, lib/python/flame/mode/horizontal/oort/trainer.py, lib/python/flame/mode/horizontal/syncfl/middle_aggregator.py, lib/python/flame/mode/horizontal/syncfl/top_aggregator.py, lib/python/flame/mode/horizontal/syncfl/trainer.py, lib/python/flame/mode/hybrid/trainer.py, lib/python/flame/mode/tasklet.py
When a class is inherited, the current compose() function doesn't reuse the tasklets created from the parent class. Therefore, a developer needs to create many of the same tasklets so that they can be chained (hence, composed). This duplicates the code.
To avoid this redundancy, the composer is extended such that the parent's tasklets are retrieved with alias used when they were created in the parent class.
To demonstrate this feature, the compose() method of top_aggregator in asyncfl mode is modified. All other examples still follow the old way of duplicating the code. Those can be revised over time.
=> feat: optimize composer's extensibility

lib/python/flame/common/util.py, lib/python/flame/config.py, lib/python/flame/datasampler/__init__.py, lib/python/flame/datasampler/default.py, lib/python/flame/datasampler/fedbalancer.py, lib/python/flame/datasampler/util.py, lib/python/flame/datasamplers.py, lib/python/flame/end.py, lib/python/flame/examples/fedbalancer_mnist/README.md, lib/python/flame/examples/fedbalancer_mnist/__init__.py, lib/python/flame/examples/fedbalancer_mnist/aggregator/__init__.py, lib/python/flame/examples/fedbalancer_mnist/aggregator/main.py, lib/python/flame/examples/fedbalancer_mnist/config/agg_template.json, lib/python/flame/examples/fedbalancer_mnist/config/train_template.json, lib/python/flame/examples/fedbalancer_mnist/run.py, lib/python/flame/examples/fedbalancer_mnist/trainer/__init__.py, lib/python/flame/examples/fedbalancer_mnist/trainer/main.py, lib/python/flame/mode/horizontal/syncfl/top_aggregator.py, lib/python/flame/mode/horizontal/syncfl/trainer.py, lib/python/flame/mode/message.py
Add a new category, "sampler", which selects trainers' data at FL rounds.
Add FedBalancer (Jaemin Shin et al., FedBalancer: Data and Pace Control for Efficient Federated Learning on Heterogeneous Clients, MobiSys'22) as a new sampler, which actively selects more important training samples of trainers to speed up global FL. Implement a control scheme of "deadline", which is only used for fedbalancer's sample selection at this version. Deadline-based round termination will be supported in later updates.
Refer to lib/python/flame/examples/fedbalancer_mnist/ for example of running fedbalancer
Things that current version of fedbalancer do not support:
- Advanced trainer selection with Oort proposed in FedBalancer
- Other FL modes: hybrid, hierarchical
Please provide a meaningful description of …
=> example/implementation for FedBalancer, with a new sampler category

lib/python/flame/channel.py, lib/python/flame/examples/coord_hier_syncfl_mnist/coordinator/config.json, lib/python/flame/examples/coord_hier_syncfl_mnist/middle_aggregator/config1.json, lib/python/flame/examples/coord_hier_syncfl_mnist/middle_aggregator/config2.json, lib/python/flame/examples/coord_hier_syncfl_mnist/top_aggregator/config.json, lib/python/flame/examples/coord_hier_syncfl_mnist/trainer/config1.json, lib/python/flame/examples/coord_hier_syncfl_mnist/trainer/config2.json, lib/python/flame/mode/horizontal/coord_syncfl/coordinator.py, lib/python/flame/mode/horizontal/coord_syncfl/middle_aggregator.py, lib/python/flame/mode/horizontal/coord_syncfl/top_aggregator.py, lib/python/flame/mode/horizontal/coord_syncfl/trainer.py, lib/python/flame/mode/message.py
The coordinated FL is resived. The key changes are:
1) The coordinator has full responsibility of informing the end of the training to the workers of all roles (top agg, mid agg and trainer).
2) The top aggregator now receives from the coordinator a list of middle aggregators that it can interact with. This can prevent the top aggregator from sending a global model to the middle aggregators which don't have any trainers. This improves efficiency by avoiding unnecessary data communication. It may help to support serverless fl case.
3) For (1), the coordinator expects the rounds information in its config file.
4) The coordinator and middle aggregator can exchange meta information. The middle aggregator can share extra information for its load or resource utilization, etc. This kind of …
=> feat: coordination revision

examples/syncfl_hier_coord_mnist/schema.json
To make funcTags easy to understand, the names of funcTags in the SDK for coordinated architecture were updated. The example in the control plane is thus outdated. The funcTags names in the schema.json are updated accordingly.
=> chore: syncfl_hier_coord_mnist schema update

lib/python/flame/mode/composer.py, lib/python/flame/mode/enums.py, lib/python/flame/mode/horizontal/coord_syncfl/middle_aggregator.py, lib/python/flame/mode/horizontal/coord_syncfl/top_aggregator.py, lib/python/flame/mode/horizontal/coord_syncfl/trainer.py, lib/python/flame/mode/horizontal/syncfl/middle_aggregator.py, lib/python/flame/mode/horizontal/syncfl/trainer.py, lib/python/flame/mode/tasklet.py
This PR improves the extensibility of tasklet composition by allowing the developer to extend the tasklet set on the original `Composer` by declaring new tasklets under `CloneComposer` context and then use the composer to get originally implmented tasklets by alias and perform composition on them. Implemented tasklet/composer operations:
- `insert_before` which inserts a tasklet before the target tasklet
- `insert_after` which inserts a tasklet after the target tasklet
- `replace_with` which replaces the target tasklet with the new tasklet
- `remove` which removes the target tasklet
The implemented operations work with loop edges, except for `remove` which will raise NotImplementedError if the target tasklet has loop edges.
This PR demonstrates the extensibility of tasklet composition by …
=> Impove tasklet composition extensibility

lib/python/flame/backend/p2p.py, lib/python/flame/channel.py
tx task termination is slow because putting EMPTY_PAYLOAD was never executed. This was because channel.remove(end) is called that end is going to be removed. Hence, the length of channel._ends is always zero. To address the issue, in channel.remove(), puting EMPTY_PAYLOAD into the tx queue is implemented. With this, every time channel.remove() is called, the given end's tx task is safely terminated.
=> fix: slow tx task termination

lib/python/flame/mode/horizontal/coord_syncfl/middle_aggregator.py, lib/python/flame/mode/horizontal/coord_syncfl/trainer.py
Add aliases for clone_compose created tasks for the coord_synfl mode.
=> Fix alias already exists for coord_syncfl

cmd/flamectl/resources/task/task.go, pkg/openapi/apiserver/api_jobs_service.go
The `flamectl get tasks <job_id>` command was failing with the status code 400 meaning that no tasks were found. 
But what really was happening was that in the URL we forgot to put a required value based on the URL format.
After adding the missing values, the command started to work sa expected
=> fix: Resolve the get tasks command by job ID to return the expected tasks details of a job

lib/python/flame/mode/composer.py, lib/python/flame/mode/distributed/trainer.py, lib/python/flame/mode/horizontal/coord_syncfl/top_aggregator.py, lib/python/flame/mode/horizontal/feddyn/top_aggregator.py, lib/python/flame/mode/horizontal/feddyn/trainer.py, lib/python/flame/mode/horizontal/oort/top_aggregator.py, lib/python/flame/mode/horizontal/syncfl/top_aggregator.py, lib/python/flame/mode/horizontal/syncfl/trainer.py, lib/python/flame/mode/hybrid/trainer.py, lib/python/flame/mode/role.py, lib/python/flame/mode/tasklet.py, lib/python/flame/monitor/__init__.py, lib/python/flame/monitor/metric_collector.py, lib/python/flame/monitor/runtime.py
Using a decorator created in flame/monitor/util.py, tasklets now can send runtime information to a MetricCollector in a composer. This allows for runtime metrics to be stored in the MetricCollector instance.
Additionally, some imports in mode/oort have been adjusted.
=> feat: track tasklet runtime

lib/python/flame/channel.py, lib/python/flame/monitor/metric_collector.py
Metric collection was added for communication costs. This included changes to flame/mode/channel.py to track the sizes of messages and also changes to flame/monitor/metric_collector.py in order to be able to accumulate a metric over the course of a round.
metric_collector.py was also slightly refactored in order to generate keys in a separate class method.
=> feat: communication cost metric collection

cmd/controller/app/database/mongodb/task.go, fiab/helm-chart/control/values.yaml
optimized create job task of control plane by changing the DB write task to insert multiple entries in batch, instead of original method of inserting one by one. changing it to insert multiple entries at once at DB makes the overall create job procedure faster. in addition, nginx timeout and message size parameters are updated for scalable create job task.
=> refactor: optimize create job task of control plane

lib/python/flame/mode/horizontal/asyncfl/middle_aggregator.py, lib/python/flame/mode/horizontal/asyncfl/top_aggregator.py, lib/python/flame/mode/horizontal/feddyn/top_aggregator.py, lib/python/flame/mode/horizontal/oort/top_aggregator.py, lib/python/flame/mode/horizontal/syncfl/middle_aggregator.py, lib/python/flame/mode/horizontal/syncfl/top_aggregator.py
Python diskcache, which we use for aggregating trainer updates, have its own automatic eviction policy, depending on its size_limit and cull_limit value. Updated it to disable automatic eviction, and added a logger debug line that tells you the number of updates in the cache.
=> fix: disable automatic eviction of diskcache at aggregation

lib/python/flame/monitor/metric_collector.py
Both threads for CPU and GPU monitoring were set to daemon=True. Previously, they were not terminating with the rest of the process.
=> fix: GPU/CPU monitoring termination

lib/python/setup.py
The protobuf version specified in setup.py leads to an error during installation. Going forward, an upgraded version of tensorflow (2.12.0) is needed for flame.
=> fix: protobuf version error

cmd/deployer/app/monitor_jobs.go, cmd/deployer/app/resource_handler.go
Deployer monitoring functionality does more than it has to do. Deployer only needs to monitor pod. If pod failed, it needs to send that signal to the control plane. It shouldn't update job's status. Currently, in case of pod failure, it directly updates task's status, which is not ideal, either.
TODO: We need a mechanism to inform the control plane of pod failure separately so that the control plane can make a final update on task's status correctly by combining all the information (whether the task itself failed, which caused pod failure or pod itself couldn't run, hence pod failure).
=> refactor: monitoring scope adjustment in deployer

lib/python/flame/registry/local.py
The timestamp of when the metric is saved is added as a second column to each per-round metric csv in the local registry.
=> feat: local registry timestamp

cmd/deployer/app/deployer/k8s.go, cmd/deployer/app/monitor.go, cmd/deployer/app/resource_handler.go
After deployer uninstall pods, it doesn't stop monitoring. Thus, the deployer thinks that pods' status is unknown and updates tasks' status as fail. This bug is fixed.
=> fix: incorrect task status update by deployer

lib/python/flame/channel.py
Aggregators sometimes send empty messages at the end of training. Previously, the trainer would throw an error when attempting to get the number of bytes received from an empty message. This is fixed by checking for an empty payload.
=> fix: check payload before accumulating bytes received

lib/python/flame/config.py
The field misc (of type dict) was added to the config file so that users can add more hyperparamters that are not otherwise supported in the format.
=> feat: allow misc field in config file

lib/python/examples/hybrid/aggregator/main.py, lib/python/flame/mode/distributed/trainer.py, lib/python/flame/mode/hybrid/top_aggregator.py, lib/python/flame/mode/hybrid/trainer.py, lib/python/flame/mode/message.py
changed the hybrid FL's aggregation to not use member check before ring-reduce anymore, instead use the information given by the top-aggregator. To this end, a new top-aggregator is introduced for Hybrid FL, which sends out the information to the ends about which ends to communicate with during ring-reduce.
=> fix: hybrid FL aggregation process without member check

cmd/flamectl/resources/job/job.go
flamectl's job udpate code was not updated when modelSpec and dataSpec were introduced. Therefore, the job update code produces incorrect configuraiton. This bug is now fixed in flamectl code.
=> fix: flamectl job update

lib/python/flame/channel.py, lib/python/setup.py
recv_fifo() takes first_k as one of its arguments to determine the first_k number of messages are received and returned.
To implement the functionality, asynchronous call
_streamer_for_recv_fifo() was implemented. However the function has a bug that is triggered in asyncfl. The function adds the first_k messages into an rx queue and re-adds the remaining messages to the head of each corresponding end id's rx queue. The remaining messages then processed in the next recv_fifo call. However, since _streamer_for_recv_fifo() is an asynchronous call, there is no guarantee that the messages saved in the previous call will be processed first. This causes some trainers blocked and made them fail to participate future rounds.
The issue is fixed as follows. Since recv_fifo() always returns first_k …
=> fix: recv_fifo for asyncfl

lib/python/flame/mode/distributed/trainer.py, lib/python/flame/mode/horizontal/coord_syncfl/coordinator.py, lib/python/flame/mode/horizontal/oort/trainer.py, lib/python/flame/mode/horizontal/syncfl/top_aggregator.py, lib/python/flame/mode/horizontal/syncfl/trainer.py, lib/python/flame/mode/hybrid/trainer.py
After metrics are reported (usually every round in the save_metrics method) they are cleared. This prevents a metric from being reported more than it should be.
Additionally, in order to properly report runtime-related metrics, the alias field was specified on all tasklets.
=> fix: clear metrics and tasklet alias

.gitmodules, lib/python/setup.py, third_party/README.md, third_party/fedscale_dataset_partitioner.py
1. This update includes a helper script to partition the FedScale dataset to Flame's trainers based on the real client-data mapping (provided by FedScale). 
2. This update also adds FedScale@7ec441c as a submodule for the use of its `download.sh` to download datasets.
3. Adding pip package `fedscale` (version 1.0) to setup.py
=> Adding FedScale dataset partitioner

docs/prerequisites.md, lib/python/flame/mode/horizontal/eager_syncfl/middle_aggregator.py, lib/python/flame/mode/horizontal/eager_syncfl/top_aggregator.py
This PR is to optimize eager aggregation mode by reducing the deepcopy of base weights. This improved implementation only requires one deepcopy operation per round. This PR also updates the suggested GoLang version in [prerequisites.md](https://github.com/cisco-open/flame/compare/main...ucr-serverless:flame:eager_agg_opt?expand=1#diff-62bb42a945e73c6607642b8ca0b796633542e7491d6661520a311e943f313806).
=> Optimizing Eager Aggregation

lib/python/flame/backend/mqtt.py
Paho MQTT v2.x requires explicit callback_api_version. Without this, instantiating mqtt.Client raises a ValueError. This change ensures compatibility with recent versions of the Paho MQTT library.
=> fix: add callback_api_version for Paho MQTT v2.x compatibility
